name: CI-config

on:
  push:
    branches:
      - lab4
      - 'lab4_autotests*'
  pull_request:
    branches:
      - lab4
      - 'lab4_autotests*'
jobs:
  pipeline:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: checkout-code
      uses: actions/checkout@v7

    - name: Lint Dockerfile
      uses: hadolint/hadolint-action@v3.1.0
      continue-on-error: true
      with:
        dockerfile: Dockerfile
        failure-threshold: warning

    - name: setup-python
      uses: actions/setup-python@v7
      with:
        python-version: '3.13'

    - name: install-requirements
      run: |
        pip install -r requirements.txt
        playwright install --with-deps chromium

    - name: build-image-for-ci
      run: docker build -t catty-reminders-app:ci .

    - name: start-stack
      run: |
        docker compose -f docker-compose.yaml -f docker-compose.ci.yaml up -d
        docker compose -f docker-compose.yaml -f docker-compose.ci.yaml ps

    - name: show-app-logs
      if: always()
      run: |
        docker compose -f docker-compose.yaml -f docker-compose.ci.yaml ps
        docker compose -f docker-compose.yaml -f docker-compose.ci.yaml logs app
        docker compose -f docker-compose.yaml -f docker-compose.ci.yaml logs db

    - name: start-tests
      env:
        PYTHONPATH: ${{ github.workspace }}
        BASE_URL: http://localhost:8181
      run: python -m pytest tests/ --junitxml=test_result.xml

    - name: stop-stack
      run: docker compose -f docker-compose.yaml -f docker-compose.ci.yaml down -v

    - name: save-artifact
      uses: actions/upload-artifact@v7
      with:
        name: test_result
        path: test_result.xml

    - name: tag-image
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ghcr.io/victorgolenkov/catty-reminders-app
        tags: |
          type=raw,value=${{ github.sha }}
          type=raw,value=latest

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v4
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: create-image
      uses: docker/build-push-action@v7
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        build-args: DEPLOY_REF=${{ github.sha }}
