name: CI-config

on:
  push:
  pull_request:

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: checkout-code
      uses: actions/checkout@v7

    - name: setup-python
      uses: actions/setup-python@v7
      with:
        python-version: '3.13'

    - name: install-requirements
      run: |
        pip install -r requirements.txt
        playwright install --with-deps chromium

    - name: run-catty-app
      run: |
        uvicorn app.main:app --host 0.0.0.0 --port 8181 &
        sleep 5

    - name: start-tests
      run: pytest tests/ --junitxml=test_result.xml

    - name: save-artifact
      uses: actions/upload-artifact@v7
      with:
        path: test_result.xml
