name: CD-config

on:
  release:
    types: [published]

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: checkout-code
      uses: actions/checkout@v7
      with:
        fetch-depth: 0

    - name: setup-python
      uses: actions/setup-python@v7
      with:
        python-version: '3.13'

    - name: install-requirements
      run: |
        pip install -r requirements.txt
        playwright install --with-deps chromium

    - name: get-commit-hash
      run: |
        TAG=${{ github.event.release.tag_name }}
        HASH=$(git rev-list -n 1 $TAG)
        echo "RELEASE_HASH=$HASH" >> $GITHUB_ENV
        echo "Release hash: $HASH"

    - name: execute-remote-SSH-commands
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ vars.HOST }}
        username: ${{ vars.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ vars.PORT }}
        script: |
          set -e
          cd /home/victor/Desktop/DevOps/Lab_1/catty-reminders-app
          git fetch origin --tags
          git checkout ${{ env.RELEASE_HASH }}

          DEPLOY_REF=$(git rev-parse HEAD)
          echo "DEPLOY_REF=$DEPLOY_REF" > .env.deploy
          echo "Deployed version: $DEPLOY_REF"

          if [ -f "requirements.txt" ]; then
              source venv/bin/activate
              pip install -r requirements.txt
          fi

          sudo /usr/bin/systemctl restart catty-app
          sleep 4

          if sudo systemctl is-active --quiet catty-app; then
              echo "Deployment completed successfully"
          else
              echo "ERROR: Application failed to start"
              exit 1
          fi
